package autonoma.DemoTienda.views;

import autonoma.DemoTiend.models.Tienda;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 * @author DOSSA0110
 * @version 1.0.0
 * @since 2024/03/14
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Tienda tienda;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Tienda tienda) {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/DemoTienda/img/TiendaImg.png")).getImage());
        }catch(Exception e){
            
        }
        this.tienda = tienda;
        this.NombreTienda.setText(this.tienda.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarProducto1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NombreTienda = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMostrarInventario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        btnAgregarProducto1.setBackground(new java.awt.Color(17, 72, 76));
        btnAgregarProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProducto1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProducto1MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Agregar Producto");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/DemoTienda/img/AgregarImg.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarProducto1Layout = new javax.swing.GroupLayout(btnAgregarProducto1);
        btnAgregarProducto1.setLayout(btnAgregarProducto1Layout);
        btnAgregarProducto1Layout.setHorizontalGroup(
            btnAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarProducto1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(btnAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarProducto1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarProducto1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14))))
        );
        btnAgregarProducto1Layout.setVerticalGroup(
            btnAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarProducto1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 380));

        jPanel1.setBackground(new java.awt.Color(17, 72, 76));

        NombreTienda.setFont(new java.awt.Font("Bernard MT Condensed", 0, 36)); // NOI18N
        NombreTienda.setForeground(new java.awt.Color(255, 255, 255));
        NombreTienda.setText("Burrosmania");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(NombreTienda)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(NombreTienda)
                .addGap(42, 42, 42))
        );

        jPanel2.setBackground(new java.awt.Color(28, 126, 108));

        btnAgregarProducto.setBackground(new java.awt.Color(17, 72, 76));
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Agregar Producto");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/DemoTienda/img/AgregarImg.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarProductoLayout = new javax.swing.GroupLayout(btnAgregarProducto);
        btnAgregarProducto.setLayout(btnAgregarProductoLayout);
        btnAgregarProductoLayout.setHorizontalGroup(
            btnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarProductoLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(btnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarProductoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarProductoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))))
        );
        btnAgregarProductoLayout.setVerticalGroup(
            btnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarProductoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        btnMostrarInventario.setBackground(new java.awt.Color(17, 72, 76));
        btnMostrarInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarInventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarInventarioMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Mostrar Inventario");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/DemoTienda/img/MostrarInventarioImg.png"))); // NOI18N

        javax.swing.GroupLayout btnMostrarInventarioLayout = new javax.swing.GroupLayout(btnMostrarInventario);
        btnMostrarInventario.setLayout(btnMostrarInventarioLayout);
        btnMostrarInventarioLayout.setHorizontalGroup(
            btnMostrarInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarInventarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(btnMostrarInventarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMostrarInventarioLayout.setVerticalGroup(
            btnMostrarInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarInventarioLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        btnBuscarProducto.setBackground(new java.awt.Color(17, 72, 76));
        btnBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarProductoMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bernard MT Condensed", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Buscar Producto");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/DemoTienda/img/BuscarImg.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarProductoLayout = new javax.swing.GroupLayout(btnBuscarProducto);
        btnBuscarProducto.setLayout(btnBuscarProductoLayout);
        btnBuscarProductoLayout.setHorizontalGroup(
            btnBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarProductoLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(btnBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        btnBuscarProductoLayout.setVerticalGroup(
            btnBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarProductoLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnMostrarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseEntered
        this.mouseEntred(btnAgregarProducto);
    }//GEN-LAST:event_btnAgregarProductoMouseEntered

    private void btnAgregarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseExited
      this.mouseExited(btnAgregarProducto);
    }//GEN-LAST:event_btnAgregarProductoMouseExited

    private void btnAgregarProducto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProducto1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto1MouseEntered

    private void btnAgregarProducto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProducto1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProducto1MouseExited

    private void btnMostrarInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarInventarioMouseEntered
        this.mouseEntred(btnMostrarInventario);
    }//GEN-LAST:event_btnMostrarInventarioMouseEntered

    private void btnMostrarInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarInventarioMouseExited
        this.mouseExited(btnMostrarInventario);
    }//GEN-LAST:event_btnMostrarInventarioMouseExited

    private void btnBuscarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProductoMouseEntered
        this.mouseEntred(btnBuscarProducto);
    }//GEN-LAST:event_btnBuscarProductoMouseEntered

    private void btnBuscarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProductoMouseExited
        this.mouseExited(btnBuscarProducto);
    }//GEN-LAST:event_btnBuscarProductoMouseExited

    private void btnAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseClicked
        System.out.println("Agregar Producto");
    }//GEN-LAST:event_btnAgregarProductoMouseClicked

    private void btnMostrarInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarInventarioMouseClicked
        System.out.println("Mostrar Inventario");
    }//GEN-LAST:event_btnMostrarInventarioMouseClicked

    private void btnBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProductoMouseClicked
        System.out.println("Buscar Producto");
    }//GEN-LAST:event_btnBuscarProductoMouseClicked

    private void mouseEntred(JPanel panel){
        panel.setBackground(new Color(17,72,76));
    }
    private void mouseExited(JPanel panel){
        panel.setBackground(new Color(0,82,82));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreTienda;
    private javax.swing.JPanel btnAgregarProducto;
    private javax.swing.JPanel btnAgregarProducto1;
    private javax.swing.JPanel btnBuscarProducto;
    private javax.swing.JPanel btnMostrarInventario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
